/** @file PrecompiledHeader.cpp
 * @brief Implementation of helpers for the optional precompiled header (see PrecompiledHeader.h). */

#include "PrecompiledHeader.h"

#include <algorithm>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <map>
#include <mutex>
#include <set>
#include <sstream>
#include <system_error>

namespace fs = std::filesystem;

namespace viz::plugins::pch
{
namespace
{
std::string toLower(std::string text)
{
    std::ranges::transform(text, text.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return text;
}

std::string firstLine(const std::string& text)
{
    return text.substr(0, text.find_first_of("\r\n"));
}

std::string readTextFile(const fs::path& path)
{
    std::ifstream input(path, std::ios::binary);
    std::ostringstream buffer;
    buffer << input.rdbuf();
    return buffer.str();
}

std::string replaceAll(std::string text, const std::string& from, const std::string& to)
{
    if (from.empty())
        return text;
    for (std::size_t pos = 0; (pos = text.find(from, pos)) != std::string::npos; pos += to.size())
    {
        text.replace(pos, from.size(), to);
    }
    return text;
}
} // namespace

const char* toString(CompilerFamily family)
{
    switch (family)
    {
    case CompilerFamily::Clang:
        return "clang";
    case CompilerFamily::Gcc:
        return "gcc";
    case CompilerFamily::Unknown:
        break;
    }
    return "unknown";
}

CompilerIdentity parseCompilerIdentity(const std::string& versionOutput)
{
    CompilerIdentity identity;
    identity.versionLine = firstLine(versionOutput);

    const std::string lower = toLower(versionOutput);
    if (lower.find("clang") != std::string::npos)
    {
        identity.family = CompilerFamily::Clang;
    }
    else if (lower.find("g++") != std::string::npos || lower.find("gcc") != std::string::npos ||
             lower.find("free software foundation") != std::string::npos)
    {
        identity.family = CompilerFamily::Gcc;
    }
    return identity;
}

CompilerIdentity identifyCompiler(const std::string& compilerPath)
{
#ifdef _WIN32
    (void)compilerPath;
    return {};
#else
    static std::mutex mutex;
    static std::map<std::string, CompilerIdentity> cache;
    {
        std::lock_guard lock(mutex);
        if (const auto it = cache.find(compilerPath); it != cache.end())
            return it->second;
    }

    // Names such as "g++" may be symlinks to clang (as in the AppImage), so only the real output is trusted
    std::string output;
    const std::string command = quote(compilerPath) + " --version 2>&1";
    if (FILE* pipe = popen(command.c_str(), "r"))
    {
        char buffer[512];
        while (std::fgets(buffer, sizeof(buffer), pipe) && output.size() < 8192)
        {
            output += buffer;
        }
        pclose(pipe);
    }

    const CompilerIdentity identity = parseCompilerIdentity(output);
    {
        std::lock_guard lock(mutex);
        cache[compilerPath] = identity;
    }
    return identity;
#endif
}

std::string commonIncludeDirectives()
{
    return "#include <iostream>\n"
           "#include <memory>\n"
           "#include <string>\n"
           "\n"
           "#ifdef _WIN32\n"
           "    #include <windows.h>\n"
           "#endif\n"
           "\n"
           "#include \"visualiserProxy/SceneWidgetVisualizerProxy.h\"\n"
           "#include \"visualiserProxy/SceneWidgetVisualizerFactory.h\"\n";
}

std::string headerFileContent()
{
    return "// Generated by OOpenCal-Viewer (--buildPrecompiledHeader), do not edit.\n"
           "// Everything which every generated model wrapper includes before the header of the model.\n"
           "#ifndef OOPENCAL_VIEWER_PRECOMPILED_H\n"
           "#define OOPENCAL_VIEWER_PRECOMPILED_H\n"
           "\n" +
           commonIncludeDirectives() +
           "\n"
           "#endif // OOPENCAL_VIEWER_PRECOMPILED_H\n";
}

std::string wrapperPreamble()
{
    const std::string header = HEADER_FILE_NAME;
    return "// Optional precompiled header: when " + header + " is on the include path it already contains\n"
           "// every header listed in the #ifndef part below (g++ picks its .gch up, clang gets -include-pch).\n"
           "#if defined(__has_include)\n"
           "#  if __has_include(\"" + header + "\")\n"
           "#    include \"" + header + "\"\n"
           "#    define OOPENCAL_VIEWER_PRECOMPILED_HEADER_USED\n"
           "#  endif\n"
           "#endif\n"
           "\n"
           "#ifndef OOPENCAL_VIEWER_PRECOMPILED_HEADER_USED\n" +
           commonIncludeDirectives() +
           "#endif // OOPENCAL_VIEWER_PRECOMPILED_HEADER_USED\n"
           "\n";
}

std::string artifactFileName(CompilerFamily family)
{
    switch (family)
    {
    case CompilerFamily::Clang:
        return std::string(HEADER_FILE_NAME) + ".pch";
    case CompilerFamily::Gcc:
        return std::string(HEADER_FILE_NAME) + ".gch";
    case CompilerFamily::Unknown:
        break;
    }
    return {};
}

std::string manifestFileName(CompilerFamily family)
{
    return std::string("OOpenCalViewerPrecompiled.") + toString(family) + ".manifest";
}

std::string stripLinkerOnlyFlags(const std::string& flags)
{
    std::istringstream stream(flags);
    std::string token;
    std::string result;
    while (stream >> token)
    {
        if (token == "-shared")
            continue;
        if (!result.empty())
            result += ' ';
        result += token;
    }
    return result;
}

std::string relocationRootFromEnvironment()
{
    const char* includeDir = std::getenv("COMPILER_INCLUDEDIR");
    if (!includeDir || *includeDir == '\0')
        return {};

    std::string value = includeDir;
    while (value.size() > 1 && value.back() == '/')
    {
        value.pop_back();
    }
    return fs::path(value).parent_path().string();
}

std::string normalizePaths(std::string text, const std::string& root)
{
    return replaceAll(std::move(text), root, ROOT_PLACEHOLDER);
}

std::string denormalizePaths(std::string text, const std::string& root)
{
    return replaceAll(std::move(text), ROOT_PLACEHOLDER, root);
}

std::string quote(const std::string& path)
{
    if (path.find(' ') == std::string::npos && path.find('"') == std::string::npos)
        return path;
    return "\"" + path + "\"";
}

std::string buildFlags(CompilerFamily family,
                       const std::string& header,
                       const std::string& artifact,
                       const std::string& dependencyFile,
                       const std::string& root)
{
    std::string flags = " -x c++-header";
    if (family == CompilerFamily::Clang && !root.empty())
    {
        // Paths below the root are stored relative to it, so the file stays valid after moving the toolchain
        flags += " -Xclang -relocatable-pch -isysroot " + quote(root);
    }
    flags += " -MD -MF " + quote(dependencyFile) + " " + quote(header) + " -o " + quote(artifact);
    return flags;
}

std::string usageFlags(CompilerFamily family, const std::string& directory, const std::string& root)
{
    std::string flags = " -I" + quote(directory);
    if (family == CompilerFamily::Clang)
    {
        // clang does not look for .pch files on #include, it has to be told explicitly
        flags += " -include-pch " + quote((fs::path(directory) / artifactFileName(family)).string());
        if (!root.empty())
        {
            // An explicit -isysroot also overrides the one implied by --sysroot, which would break relocation
            flags += " -isysroot " + quote(root);
        }
    }
    return flags;
}

std::string probeFlags(CompilerFamily family,
                       const std::string& directory,
                       const std::string& root,
                       const std::string& probeSource)
{
    std::string flags = usageFlags(family, directory, root);
    if (family == CompilerFamily::Gcc)
    {
        // g++ silently ignores a .gch it cannot use; turn it into an error for the self-test
        flags += " -Winvalid-pch -Werror=invalid-pch";
    }
    flags += " -fsyntax-only " + quote(probeSource);
    return flags;
}

std::string previewUsageFlags(const std::string& directory, CompilerFamily family, const std::string& root)
{
    if (directory.empty() || family == CompilerFamily::Unknown)
        return {};

    std::error_code ec;
    if (!fs::is_regular_file(fs::path(directory) / artifactFileName(family), ec))
        return {};
    return usageFlags(family, directory, root);
}

std::vector<std::string> parseMakeDependencies(const std::string& dependencyFileText)
{
    // 1. join continuation lines
    std::string joined;
    for (std::size_t i = 0; i < dependencyFileText.size(); ++i)
    {
        const char c = dependencyFileText[i];
        if (c == '\\' && i + 1 < dependencyFileText.size())
        {
            if (dependencyFileText[i + 1] == '\n')
            {
                joined += ' ';
                ++i;
                continue;
            }
            if (dependencyFileText[i + 1] == '\r' && i + 2 < dependencyFileText.size() && dependencyFileText[i + 2] == '\n')
            {
                joined += ' ';
                i += 2;
                continue;
            }
        }
        joined += c;
    }

    // 2. skip the target: everything up to the first unescaped ':' followed by a whitespace
    std::size_t colon = std::string::npos;
    for (std::size_t i = 0; i + 1 < joined.size(); ++i)
    {
        if (joined[i] == '\\')
        {
            ++i;
            continue;
        }
        if (joined[i] == ':' && std::isspace(static_cast<unsigned char>(joined[i + 1])))
        {
            colon = i;
            break;
        }
    }
    if (colon == std::string::npos)
        return {};

    // 3. split the prerequisites on unescaped whitespace
    std::vector<std::string> result;
    std::string current;
    for (std::size_t i = colon + 1; i < joined.size(); ++i)
    {
        const char c = joined[i];
        if (c == '\\' && i + 1 < joined.size() && joined[i + 1] == ' ')
        {
            current += ' ';
            ++i;
            continue;
        }
        if (std::isspace(static_cast<unsigned char>(c)))
        {
            if (!current.empty())
            {
                result.push_back(current);
                current.clear();
            }
            continue;
        }
        current += c;
    }
    if (!current.empty())
        result.push_back(current);
    return result;
}

std::vector<std::string> filterProjectDependencies(const std::vector<std::string>& dependencies,
                                                   const std::vector<std::string>& roots)
{
    std::vector<std::string> prefixes;
    for (const auto& root : roots)
    {
        if (root.empty())
            continue;
        std::string prefix = fs::path(root).lexically_normal().string();
        while (prefix.size() > 1 && prefix.back() == '/')
        {
            prefix.pop_back();
        }
        prefixes.push_back(prefix);
    }

    std::set<std::string> unique;
    for (const auto& dependency : dependencies)
    {
        const fs::path path = fs::path(dependency).lexically_normal();
        if (!path.is_absolute())
            continue;

        const std::string text = path.string();
        const bool underRoot = std::ranges::any_of(prefixes, [&text](const std::string& prefix) {
            return text.size() > prefix.size() && text.compare(0, prefix.size(), prefix) == 0 && text[prefix.size()] == '/';
        });
        if (underRoot)
            unique.insert(text);
    }
    return {unique.begin(), unique.end()};
}

std::string serializeManifest(const Manifest& manifest)
{
    std::ostringstream out;
    out << "# OOpenCal-Viewer precompiled header manifest (generated, do not edit)\n"
        << "format=" << manifest.format << "\n"
        << "family=" << manifest.family << "\n"
        << "compiler=" << manifest.compilerVersion << "\n"
        << "command=" << manifest.command << "\n";
    for (const auto& dependency : manifest.dependencies)
    {
        out << "dependency=" << dependency << "\n";
    }
    return out.str();
}

std::optional<Manifest> parseManifest(const std::string& text)
{
    Manifest manifest;
    manifest.format = 0;
    bool hasCommand = false;

    std::istringstream input(text);
    std::string line;
    while (std::getline(input, line))
    {
        if (!line.empty() && line.back() == '\r')
            line.pop_back();
        if (line.empty() || line.front() == '#')
            continue;

        const auto equals = line.find('=');
        if (equals == std::string::npos)
            continue;

        const std::string key = line.substr(0, equals);
        const std::string value = line.substr(equals + 1);
        if (key == "format")
        {
            try
            {
                manifest.format = std::stoi(value);
            }
            catch (const std::exception&)
            {
                return std::nullopt;
            }
        }
        else if (key == "family")
        {
            manifest.family = value;
        }
        else if (key == "compiler")
        {
            manifest.compilerVersion = value;
        }
        else if (key == "command")
        {
            manifest.command = value;
            hasCommand = true;
        }
        else if (key == "dependency")
        {
            manifest.dependencies.push_back(value);
        }
    }

    if (manifest.format != MANIFEST_FORMAT || manifest.family.empty() || !hasCommand)
        return std::nullopt;
    return manifest;
}

Usability evaluate(const std::string& directory,
                   const CompilerIdentity& compiler,
                   const std::string& expectedCommand,
                   const std::string& root)
{
    Usability result;
    if (directory.empty())
    {
        result.reason = "no directory is configured";
        return result;
    }
    if (compiler.family == CompilerFamily::Unknown)
    {
        result.reason = "the compiler is neither clang nor g++";
        return result;
    }

    const fs::path dir(directory);
    result.headerPath = (dir / HEADER_FILE_NAME).string();
    result.artifactPath = (dir / artifactFileName(compiler.family)).string();

    std::error_code ec;
    if (!fs::is_regular_file(result.headerPath, ec))
    {
        result.reason = std::string("file ") + HEADER_FILE_NAME + " is missing";
        return result;
    }
    if (!fs::is_regular_file(result.artifactPath, ec))
    {
        result.reason = "it was not built for " + std::string(toString(compiler.family)) + " (file " +
                        artifactFileName(compiler.family) + " is missing)";
        return result;
    }

    const auto manifest = parseManifest(readTextFile(dir / manifestFileName(compiler.family)));
    if (!manifest)
    {
        result.reason = "its manifest is missing or unreadable";
        return result;
    }
    if (manifest->family != toString(compiler.family))
    {
        result.reason = "it was built for " + manifest->family;
        return result;
    }
    if (manifest->compilerVersion != compiler.versionLine)
    {
        result.reason = "it was built by a different compiler (" + manifest->compilerVersion + ")";
        return result;
    }
    if (manifest->command != expectedCommand)
    {
        result.reason = "the compilation settings differ from the ones it was built with";
        return result;
    }

    const auto artifactTime = fs::last_write_time(result.artifactPath, ec);
    if (ec)
    {
        result.reason = "its modification time cannot be read";
        return result;
    }
    for (const auto& dependency : manifest->dependencies)
    {
        const std::string path = denormalizePaths(dependency, root);
        const auto dependencyTime = fs::last_write_time(path, ec);
        if (ec)
        {
            result.reason = "a header it was built from is missing: " + path;
            return result;
        }
        if (dependencyTime > artifactTime)
        {
            result.reason = "header '" + path + "' is newer than it (rebuild it with --buildPrecompiledHeader)";
            return result;
        }
    }

    result.usable = true;
    return result;
}
} // namespace viz::plugins::pch
