name: Build Qt-VTK-viewer (.deb only, system deps) [on push and release]

on:
  push:
    branches:
      - '**'
  release:
    types: [created]

env:
  PROJECT_NAME: QtVtkViewer

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      ################### checkout & dependencies
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout OOpenCAL dependency
        uses: actions/checkout@v3
        with:
          repository: alessioderango/OOpenCAL
          path: deps/OOpenCAL
          token: ${{ secrets.VisualizerOpenCal }}

      - name: Install dependencies (runtime & build)
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            qt6-base-dev \
            qt6-tools-dev \
            qt6-tools-dev-tools \
            libvtk9-dev \
            libvtk9-qt-dev \
            software-properties-common

      # - name: Install GCC 13
      #   run: |
      #     sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      #     sudo apt update
      #     sudo apt install -y gcc-13 g++-13
      #     sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 \
      #                              --slave /usr/bin/g++ g++ /usr/bin/g++-13

      ################### building application
      - name: Prepare application icon
        run: |
          mkdir -p resources/icons
          cp icons/application.png resources/icons/${PROJECT_NAME}.png || true

      - name: Create .desktop file
        run: |
          echo "[Desktop Entry]
          Name=${PROJECT_NAME}
          Exec=${PROJECT_NAME}
          Icon=${PROJECT_NAME}
          Type=Application
          Categories=Utility;Science;" > ${PROJECT_NAME}.desktop

      - name: Build application
        run: |
          mkdir -p build
          cd build
          cmake .. -DOOPENCAL_DIR=${{ github.workspace }}/deps
          cmake --build . --parallel

      ################### build .deb (with runtime Depends only, no libs bundled)
      - name: Build .deb package (system dependencies only)
        run: |
          set -euo pipefail
          PKG_DIR="debian/${PROJECT_NAME}"
          mkdir -p "${PKG_DIR}/usr/bin"
          mkdir -p "${PKG_DIR}/usr/share/applications"
          mkdir -p "${PKG_DIR}/usr/share/icons/hicolor/256x256/apps"
          mkdir -p "${PKG_DIR}/DEBIAN"

          # Copy binary
          cp build/${PROJECT_NAME} "${PKG_DIR}/usr/bin/${PROJECT_NAME}"
          chmod +x "${PKG_DIR}/usr/bin/${PROJECT_NAME}"

          # Copy desktop & icon
          cp ${PROJECT_NAME}.desktop "${PKG_DIR}/usr/share/applications/" || true
          cp resources/icons/${PROJECT_NAME}.png "${PKG_DIR}/usr/share/icons/hicolor/256x256/apps/${PROJECT_NAME}.png" || true

          # Version
          if [[ "${GITHUB_REF_TYPE:-}" == "tag" ]]; then
            VERSION="$(echo "${GITHUB_REF_NAME}" | sed 's/^v//')"
          else
            VERSION="0.0.1+git"
          fi

          # Control file with fixed Depends
          printf "%s\n" \
            "Package: ${PROJECT_NAME}" \
            "Version: ${VERSION}" \
            "Section: science" \
            "Priority: optional" \
            "Architecture: amd64" \
            "Maintainer: YourName <your@email>" \
            "Depends: libvtk9-dev, libvtk9-qt-dev, qt6-base-dev, libstdc++6, libc6" \
            "Description: ${PROJECT_NAME} - Qt + VTK scientific viewer (system VTK)" \
            > "${PKG_DIR}/DEBIAN/control"

          dpkg-deb --build "${PKG_DIR}" "${PROJECT_NAME}.deb"

      ################### artifacts
      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-deb
          path: ${{ env.PROJECT_NAME }}.deb

      ################### release upload
      - name: Upload .deb to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PROJECT_NAME }}.deb
